# Auto-generated by asn1ate v.0.6.0 from cd.asn
# (last modified on 2023-05-16 18:58:18.635044)

from pyasn1.type import univ, char, namedtype, namedval, tag, constraint, useful


from pyasn1_modules import rfc5652


class CertificationDeclaration(univ.Sequence):
    pass


CertificationDeclaration.componentType = namedtype.NamedTypes(
    namedtype.NamedType('version', univ.Integer()),
    namedtype.NamedType('digestAlgorithm', univ.ObjectIdentifier()),
    namedtype.NamedType('encapContentInfo', rfc5652.EncapsulatedContentInfo()),
    namedtype.NamedType('signerInfo', rfc5652.SignerInfo())
)
