/*
 *
 *    Copyright (c) 2024 Google LLC. All rights reserved
 */

/**
 * NOTE: This file is generated by src/tools/chip-cert/dacs.py.
 */
#pragma once
#include <cstdint>

#include <lib/support/Span.h>
#include <platform/CHIPDeviceConfig.h>

namespace google {
namespace matter {

extern const uint8_t kDevelopmentDAC_Cert_6006_B002[502];
extern const uint8_t kDevelopmentDAC_PublicKey_6006_B002[65];
extern const uint8_t kDevelopmentDAC_PrivateKey_6006_B002[32];

}
}