/*
 *
 *    Copyright (c) 2024 Google LLC. All rights reserved
 */

/**
 * NOTE: This file is generated by src/tools/chip-cert/dacs.py.
 */
#pragma once
#include <cstdint>

#include <lib/support/Span.h>
#include <platform/CHIPDeviceConfig.h>

namespace google {
namespace matter {
    
extern const uint8_t kDevelopmentPAI_Cert_6006[442];
extern const uint8_t kDevelopmentPAI_PublicKey_6006[65];
extern const uint8_t kDevelopmentPAI_PrivateKey_6006[32];

} // namespace matter
} // namespace google
